question_flow:
  subject1:
    conditions:
    - condition: value == 'no'
      skip_questions:
      - subject2
      - subject3
      - subject4
      - subject5
      - subject6
      - subject7
      - action1
      - action2
      inherited_skip: true
  context1:
    conditions:
    - condition: value == 'natural resource'
      skip_questions:
      - context6
      - context7
      - context8
      - context9
      - context10
      - context11
      - context12
      - context13
      - context14
      - context15
      inherited_skip: true
    - condition: value == 'tourist attraction'
      skip_questions:
      - context2
      - context3
      - context4
      - context5
      - context6
      - context10
      - context11
      - context12
      - context13
      - context14
      - context15
      inherited_skip: true
    - condition: value == 'leisure and recreation'
      skip_questions:
      - context2
      - context3
      - context4
      - context5
      - context6
      - context7
      - context8
      - context9
      - context14
      - context15
      inherited_skip: true
    - condition: value == 'lodging facility'
      skip_questions:
      - context2
      - context3
      - context4
      - context5
      - context6
      - context7
      - context8
      - context9
      - context10
      - context11
      - context12
      - context13
      - context15
      inherited_skip: true
    - condition: value == 'infrastructure'
      skip_questions:
      - context2
      - context3
      - context4
      - context5
      - context6
      - context7
      - context8
      - context9
      - context10
      - context11
      - context12
      - context13
      - context14
      inherited_skip: true
    - condition: value == 'other'
      skip_questions:
      - context2
      - context3
      - context4
      - context5
      - context6
      - context7
      - context8
      - context9
      - context10
      - context11
      - context12
      - context13
      - context14
      - context15
      inherited_skip: true
  context2:
    conditions:
    - condition: value == 'flora'
      skip_questions:
      - context4
      - context5
      inherited_skip: false
    - condition: value == 'fauna'
      skip_questions:
      - context3
      - context5
      inherited_skip: false
    - condition: value == 'landscapes'
      skip_questions:
      - context3
      - context4
      inherited_skip: false
  context6:
    conditions:
    - condition: value == 'heritage'
      skip_questions:
      - context8
      - context9
      inherited_skip: false
    - condition: value == 'culture'
      skip_questions:
      - context7
      - context9
      inherited_skip: false
    - condition: value == 'gastronomy'
      skip_questions:
      - context7
      - context8
      inherited_skip: false
  context10:
    conditions:
    - condition: value == 'other leisure activities'
      skip_questions:
      - context12
      - context13
      inherited_skip: false
    - condition: value == 'sports'
      skip_questions:
      - context11
      - context13
      inherited_skip: false
    - condition: value == 'shopping'
      skip_questions:
      - context11
      - context12
      inherited_skip: false
